[workspace]
members  = ["crates/synth-tui", "crates/synthie"]
resolver = "3"

[workspace.package]
version    = "0.3.1"
edition    = "2024"
authors    = ["Markus Mayer <widemeadows@gmail.com>"]
repository = "https://github.com/sunsided/synth"
license    = "EUPL-1.2"

[workspace.dependencies]
anyhow            = "1"
cpal              = "0.17"
crossbeam-channel = "0.5"
crossterm         = "0.29"
libm              = "0.2"
ratatui           = "0.30"
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"

[workspace.lints.clippy]
pedantic = "warn"
